<?php

namespace filemigo\classes;

use pool\classes\Core\Input\Session;
use pool\classes\Core\Weblication;

class FilemigoApp extends Weblication
{
    private array $config = [];

    public function findTemplate(string $filename, string $classFolder = '', bool $baseLib = false): string
    {
        return parent::findTemplate($filename, $classFolder, $baseLib); // TODO: Change the autogenerated stub
    }

    public function getConfig(): array
    {
        return $this->config;
    }

    public function setConfig(array $config): void
    {
        $this->config = $config;
    }

    public function getConfigValue(string $key)
    {
        return $this->config[$key] ?? null;
    }
    public function setConfigValue(string $key, $value): void
    {
        $this->config[$key] = $value;
    }

    public function startPHPSession(
        string $session_name = 'WebAppSID',
        bool $useTransSID = false,
        bool $useCookies = true,
        bool $useOnlyCookies = false,
        bool $autoClose = true,
        string $sessionClassName = Session::class,
    ): static {
        if (session_status() === PHP_SESSION_NONE) {
            ini_set('session.cookie_secure', true);
            ini_set('session.cookie_httponly', true);
            ini_set('session.cookie_samesite', 'Strict');
        }
        return parent::startPHPSession($session_name, $useTransSID, $useCookies, $useOnlyCookies, $autoClose, $sessionClassName); // TODO: Change the autogenerated stub
    }
}