<?php
/**
 * Filemigo
 * Copyright (c) 2025 Christian Schmidseder
 *
 * This file is part of Filemigo.
 *
 * Licensed under the MIT License. See the LICENSE file
 * in the project root for full license information.
 */

namespace filemigo\classes;

use pool\classes\Core\Input\Session;
use pool\classes\Core\Weblication;

class FilemigoApp extends Weblication
{
    private array $config = [];

    public function getConfig(): array
    {
        return $this->config;
    }

    public function setConfig(array $config): void
    {
        $this->config = $config;
    }

    public function getConfigValue(string $key, $default = null)
    {
        return $this->config[$key] ?? $default;
    }

    public function setConfigValue(string $key, $value): void
    {
        $this->config[$key] = $value;
    }

    public function setup(array $settings = []): static
    {
        $settings['application.translatorResourceDir'] = DIR_RESOURCES_ROOT . '/lang';
        $settings['application.translatorStaticResourceDir'] = $settings['application.translatorResourceDir'];

        return parent::setup($settings); // TODO: Change the autogenerated stub
    }

    public function startPHPSession(
        string $session_name = 'WebAppSID',
        bool $useTransSID = false,
        bool $useCookies = true,
        bool $useOnlyCookies = true,
        bool $autoClose = true,
        string $sessionClassName = Session::class,
    ): static {
        if (session_status() === PHP_SESSION_NONE) {
            ini_set('session.cookie_secure', true);
            ini_set('session.cookie_httponly', true);
            ini_set('session.cookie_samesite', 'Strict');
        }
        return parent::startPHPSession($session_name, $useTransSID, $useCookies, $useOnlyCookies, $autoClose, $sessionClassName); // TODO: Change the autogenerated stub
    }
}