<?php

namespace filemigo\classes;

use pool\classes\Core\Weblication;
use const pool\PWD_TILL_GUIS;

class FilemigoApp extends Weblication
{
    private array $config = [];

    public function findTemplate(string $filename, string $classFolder = '', bool $baseLib = false): string
    {
        return parent::findTemplate($filename, $classFolder, $baseLib); // TODO: Change the autogenerated stub
    }

    public function getConfig(): array
    {
        return $this->config;
    }

    public function setConfig(array $config): void
    {
        $this->config = $config;
    }

    public function getConfigValue(string $key)
    {
        return $this->config[$key] ?? null;
    }
    public function setConfigValue(string $key, $value): void
    {
        $this->config[$key] = $value;
    }
}